# Site settings
title: youdriveai
email: litroncn@gmail.com
description: >
  Code2Bits is my personal site where I blog about software engineering,
  software architecture and all things I have learned in my IT career.
url: https://www.youdriveai.com
author: André Maré
baseurl: ""
twitter:
  username: code2bits
  card: summary
logo: assets/images/logo/code2bits_logo_small.png
paginate: 3
paginate_path: "blog/page:num"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
google_analytics: "UA-80779356-1"
